llm:
  model: gpt-4o
commit:
  types:
    - build
    - chore
    - ci
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  scopes:
    - cmd
    - llm
    - models
    - ui
    - utils
